
services:
  api:
    build: ./api
    ports:
      - 8080:8080
    depends_on:
      - db
      - minio

  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api

  detect:
    build: ./detect
    ports:
      - 5000:5000
    depends_on:
      - api

  alpr:
    build: ./yolo
    port:
      - 5001:5001

  db:
    container_name: db
    image: pgvector/pgvector:pg16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

volumes:
  db_data:
  minio_data:
