version: '3'
services:
  alpr:
    build: ./alpr
    ports:
      - 5000:5000

  backend:
    build: ./backend
    ports:
      - 9000:9000
    volumes:
      - "./backend/src:/app/src"
      - "./backend/db:/app/db"
      - "./backend/static:/app/static"

  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    volumes:
      - "./frontend/src:/app/src"
