version: '3'
services:
  alpr:
    build: ./alpr

  backend:
    build: ./backend
    ports:
      - 9000:9000
    volumes:
      - "./backend/src:/app/src"

  frontend:
    build: ./frontend
    ports: 
      - 3000:3000
    volumes:
      - "./frontend/src:/app/src"
