version: '3'
services:

  lpdb-server:
    build: .
    image: hanbeul/lpdb-server
    ports:
      - 80:3000
  openalpr:
    image: openalpr/openalpr
    volumes:
      - ./config:/config
    entrypoint:
      - /bin/bash
      #- alprd
      #- --config
      #- /config
      #- -f


    # command: ["python", "app.py"]
    # environment:
    #   - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672
    # volumes:
    #   - ./app:/app
    #depends_on:
    #  - mongo

    #mongo:
    #  image: mongo
    #  expose:
    #    - "27017"
